### ISSUE TITLE
Control panels can request a list of connected nodes

### ISSUE THREAD

**Issue by SmileyFace799** [odinguden/Prosjekt-IDATA2304-Gruppe-16#8]
A control panel should be able to request all the connected nodes, then receive a message containing all the currently connected nodes

**Comment by sigve10** [comment]
Control panels now send a request to all sensor nodes on the server whenever they connect, which reply by sending information about themselves to the requesting control panel. In the opposite scenario, when a sensor node connects, it sends information about itself to all control panels on the server. This ensures that all control panels have an updated list of connected nodes.
