### ISSUE TITLE
Implement node sensor update

### ISSUE THREAD

**Issue by odinguden** [odinguden/Prosjekt-IDATA2304-Gruppe-16#9]
Nodes should update control panels when one of their sensors states changes.

**Comment by sigve10** [comment]
Nodes send a notification to all control panels when their sensors update.

Once UDP is merged to the sandbox, we should aim to use UDP for these state changes, rather than TCP. Delaying closing the issue until that has been done.

**Comment by sigve10** [comment]
Closing this issue as UDP is discontinued for the time being.
